global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']  # üî• –ò–º—è –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞, –Ω–µ localhost

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']  # üî• –ò–º—è –∫–æ–Ω—Ç–µ–π–Ω–µ—Ä–∞, –Ω–µ localhost

  - job_name: 'custom_exporter'
    static_configs:
      - targets: ['host.docker.internal:8000']
    scrape_interval: 20s

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['host.docker.internal:8001']
    scrape_interval: 15s

  - job_name: 'valorant_exporter'
    static_configs:
      - targets: ['host.docker.internal:8002']
    scrape_interval: 15s